/**
 * Every raster image the video shows, with its short on-screen credit.
 * Generated by scripts/build_credits.py from the provenance sidecars in
 * public/images/*.png.json; do not edit by hand. Empty until images exist.
 */
export interface ImageMeta {
  file: string;
  /** shown in the window title bar whenever the image is on screen */
  credit: string;
}

const registry = {} satisfies Record<string, ImageMeta>;

export type ImageId = keyof typeof registry;
export const images: Record<ImageId, ImageMeta> = registry;
